### ISSUE TITLE
babel-core not found despite the fact its globally installed

### ISSUE THREAD

**Issue by Silverdust-ZH** [zenato/sbt-babel#1]
Hi there
I am working in a Windows10 environment and unfortunately, this plugin doesn't seem to work :-/
When try to create the assets using play, I get the following error:

(Server started, use Ctrl+D to stop and go back to the console...)

[info] Babel compiling on 4 source(s)
[error] module.js:338
[error]     throw err;
[error]           ^
[error] Error: Cannot find module 'babel-core'
[error]     at Function.Module._resolveFilename (module.js:336:15)
[error]     at Function.Module._load (module.js:278:25)
[error]     at Module.require (module.js:365:17)
[error]     at require (module.js:384:17)
[error]     at Object.<anonymous> (C:\Projekte\Privat\betterdating\htdocs\project\target\babel\sbt-babel-1.0.1.jar:8:9)
[error]     at Module._compile (module.js:460:26)
[error]     at Object.Module._extensions..js (module.js:478:10)
[error]     at Module.load (module.js:355:32)
[error]     at Function.Module._load (module.js:310:12)
[error]     at Function.Module.runMain (module.js:501:10)
[error] module.js:338
[error]     throw err;

Of course one would think that the problem is that the babel-core npm module isn't installed, but it actually is:

When I type "npm list -g babel-core" in a terminal, I get the following result:
C:\Users\sam\AppData\Roaming\npm
└── babel-core@5.8.23

Are there any known issues?

Best regards
Samuel

**Comment by alakiikonen** [comment]
I'm having the same issue. And adding the 
`"org.webjars.npm"           % "babel-core"           % "5.8.19",`
in build.sbt fails too, as not all dependencies can be found on org.webjars.npm

**Comment by Silverdust-ZH** [comment]
Hi alakiikonen
I finally found about the issue:
The problem is that there must be an environment vairable valled 'NODE_PATH' with value '%AppData%\npm\node_modules'

After adding this environment variable and restarting the terminal, it worked for me! :-)

**Comment by zenato** [comment]
Hi Amadeus82.
Thank you for your reports.

Another way, You can write package.json in project root.
1. wrtie [package.json].
   {
   "devDependencies": {
     "babel-core": "^5.8.19"
   }
   }
2. Run "babel" task on sbt console.
3. Create [node_modules] directory and download babel-core automacally.
   (You don't have to [babel-core] install globally and set environment.)

Thanks.
