### ISSUE TITLE
Update to use Babel 7

### ISSUE THREAD

**Issue by kevinmwangi** [zenato/sbt-babel#11]
Can have an update from 'babel-core' to '@babel/core'
Kindly let me know how in can help though am not well conversant with scala.

**Comment by kevinmwangi** [comment]
Is it as simple as changing line no 8 on this file [babel.js](https://github.com/zenato/sbt-babel/blob/master/src/main/resources/babel.js) to var babel = require("@babel/core");

**Comment by zenato** [comment]
@kevinmwangi Released sbt-babel v1.2.0 for support babel v7.

**Comment by kevinmwangi** [comment]
Thanks a tone really appreciate this
