### ISSUE TITLE
release for scala 2.12

### ISSUE THREAD

**Issue by roti** [zenato/sbt-babel#8]
Could you publish v1.1.2 for scala 2.12 as well?

**Comment by zenato** [comment]
I published v1.1.2 for scala 2.12.
Thanks for your comment.

**Comment by Enalmada** [comment]
Is 1.1.2 really published?  I wanted to try it out but when I add it to plugins I get:
io.teamscala.sbt#sbt-babel;1.1.2: not found

Just looking around I also don't seem to see it in bintray
![image](https://user-images.githubusercontent.com/1892132/37881116-bc31853a-3047-11e8-8292-793a98eba522.png)
https://bintray.com/zenato/sbt-plugins/sbt-babel

**Comment by zenato** [comment]
@Enalmada sbt-babel v1.1.2 supported sbt 1.x.
What is your sbt version?

I don't know why Bintray show sbt 0.x plugins.

**Comment by Enalmada** [comment]
@zenato I am using sbt 1.1.1.  I think when it is fully published 1.1.2 should show up on your public [bintray page ](https://bintray.com/zenato/sbt-plugins/sbt-babel).  

I don't know much about bintray but I see some 2.12 stuff when I try and navigate [manually ](https://dl.bintray.com/zenato/sbt-plugins/io.teamscala.sbt/sbt-babel/) but it doesn't appear to be public for the resolver to see.  Perhaps it is in a staging state or something?

**Comment by zenato** [comment]
@Enalmada I published again for v1.1.2.
It seems to works fine.
